//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCV.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblEgitimlerim
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez...")]
        public string Baslik { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez...")]
        public string AltBaslik { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez...")]
        [StringLength(10,ErrorMessage = "Lütfen en fazla 10 karakterlik veri girişi yapınız...")]
        public string GNO { get; set; }
        [Required(ErrorMessage = "Bu alan boş geçilemez...")]
        public string Tarih { get; set; }
    }
}
